apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyotu-project-operator.fullname" . }}
  labels:
    {{- include "kyotu-project-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kyotu-project-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.config.metrics.port }}"
        prometheus.io/path: "{{ .Values.config.metrics.path }}"
        {{- end }}
      labels:
        {{- include "kyotu-project-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyotu-project-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: GITLAB_URL
              value: {{ .Values.config.gitlabUrl }}
            - name: ARGO_REPO
              value: {{ .Values.config.argoRepo }}
            - name: FLUX_REPO
              value: {{ .Values.config.fluxRepo }}
            - name: REPO_BRANCH
              value: {{ .Values.config.repoBranch }}
            - name: ARGO_DEPLOY_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.argo.deployKeySecret }}
                  key: {{ .Values.config.argo.deployKeySecretKey }}
            - name: FLUX_DEPLOY_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.flux.deployKeySecret }}
                  key: {{ .Values.config.flux.deployKeySecretKey}}
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.gitlab.tokenSecret }}
                  key: {{ .Values.config.gitlab.tokenSecretKey }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
