apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.kyotu.tech
  namespace: default
spec:
  group: kyotu.tech
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
      - project
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                environmentType:
                  type: string
                  enum:
                  - dev
                  - test
                  - prod
              required: ["projectId", "environmentType"]
          required: ["spec"]