name: Build and push

on:
  push:
    branches: [main, '**']
    paths:
      - '**'
      - '!charts/**'
    tags:
      - '**'
      - '!helm-*'
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!charts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$PATH:$HOME/.cargo/bin"

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings  

      - name: Install cargo check tools
        run: |
          cargo install --locked cargo-deny || true
          cargo install --locked cargo-outdated || true
          cargo install --locked cargo-udeps || true
          cargo install --locked cargo-audit || true
          cargo install --locked cargo-pants || true  

      - name: Check
        run: |
          cargo deny check
          cargo outdated --exit-code 1
          cargo udeps
          rm -rf ~/.cargo/advisory-db
          cargo audit
          cargo pants 

      - name: Test
        run: cargo test

    #- name: Rust lint
    #  run: cargo clippy -- -D warnings
    #  continue-on-error: true

  # push only on tags but not on tags that start with helm- (e.g. helm-1.0.0)
  push_production:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/helm-')
    needs: build

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        cache-from: type=gha
        cache-to: type=gha
        push: true
        tags: |
         ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:${{ steps.get_version.outputs.VERSION }}
         ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:latest

    - name: Change App version in Helm Chart
      run: |
        sed -i "s/appVersion: .*/appVersion: ${{ steps.get_version.outputs.VERSION }}/g" charts/kyotu-project-operator/Chart.yaml

    - name: Push back to repo
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add charts/kyotu-project-operator/Chart.yaml
        git commit -m "Update Chart.yaml appVersion to ${{ steps.get_version.outputs.VERSION }}"
    
    - name: Push back to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true

  #push on commit to main
  push_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - name: Get short SHA
      id: get_short_sha
      run: echo ::set-output name=SHA::$(echo ${GITHUB_SHA} | cut -c1-7)

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        cache-from: type=gha
        cache-to: type=gha
        push: true
        tags: |
         ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:dev-${{ steps.get_short_sha.outputs.SHA }}
