name: Helm Chart Release

on:
  push:
    branches: [main, '*']
    tags:
      - 'helm-*'
  pull_request:
    branches: [main]
    paths:
      - 'charts/**'
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - uses: azure/setup-helm@v3
      name: Setup Helm
      with:
        version: 'v3.11.2'
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Helm lint
      run: helm lint charts/kyotu-project-operator

    - name: Create kind cluster
      if: startsWith(github.ref, 'refs/tags/helm-')
      uses: helm/kind-action@v1.4.0

    - name: Install kyotu-project-operator chart
      if: startsWith(github.ref, 'refs/tags/helm-')
      run: |
        helm install kyotu-project-operator charts/kyotu-project-operator --wait --timeout 5m

  #run only on tag push with a tag that starts with helm-* (e.g. helm-1.0.0)
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/helm-')
    needs: test

    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - uses: azure/setup-helm@v3
      name: Setup Helm
      with:
        version: 'v3.11.3'

    - name: update chart version in Chart.yaml
      run: |
        chart_version=$(echo "${GITHUB_REF}" | sed -e 's/refs\/tags\/helm-//')
        sed -i "s/^version: .*/version: ${chart_version}/" charts/kyotu-project-operator/Chart.yaml
        echo "Chart version updated to ${chart_version}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build and push Helm Chart
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      run: |
        chart_version=$(echo "${GITHUB_REF}" | sed -e 's/refs\/tags\/helm-//')
        helm package charts/kyotu-project-operator
        helm push "${{ env.ECR_REPOSITORY }}-${chart_version}.tgz" oci://$ECR_REGISTRY
    
    - name: Create commit with changed Chart.yaml
      run: |
        chart_version=$(echo "${GITHUB_REF}" | sed -e 's/refs\/tags\/helm-//')
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add charts/kyotu-project-operator/Chart.yaml
        git commit -m "Update Chart.yaml version to ${chart_version}"
        
    - name: Push back to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true